### ISSUE TITLE
Convert performTipiMethod to callWebservice

### ISSUE THREAD

**Issue by kharybdys** [Dexels/navajo#106]
We have identified a probable problem with the different between init/messagestore and InitMessagestoreData.
Also, chances are high this cannot be done fully automatical because it is difficult to match the tipiComponent with the inputService that needs to replace it.

**Comment by kharybdys** [comment]
Looks like performTipiMethod no longer exists within SLC, OAO, DWF Dashboard or TeamRegistration applications. Closing.

**Comment by kharybdys** [comment]
Oops, should wait for search to complete.
Seems to still be in use at OAO and at the KNHB-DWF (in com.sportlink.apps)

**Comment by DimitrisD** [comment]
Is this relevant to Navajo?

**Comment by kharybdys** [comment]
No, I registered what still has to be done in a better spot
