### ISSUE TITLE
Upgrade Vaadin version to Vaadin 7

### ISSUE THREAD

**Issue by flyaruu** [Dexels/navajo#120]
Vaadin 7 has a different api, so some reimlementation might be necessary.

**Comment by flyaruu** [comment]
The update path isn't trivial (at least the one from 6->7) and I fear neither is the rest. As we now only use Vaadin for one relatively simple web application (official portal), and we're not going to ever expand that, I think we should redo the official portal in the same technology we'll be using for the web-based sportlink club. In the mean time (if no urgent browser issues arise) I think the Vaadin-6 based official portal will be ok for the time being.

**Comment by DimitrisD** [comment]
I understand and agree. I'm closing this.
