### ISSUE TITLE
(Navajo) Being able to define property type for null values in navajomap.createproperty construct

### ISSUE THREAD

**Issue by aschoneveld** [Dexels/navajo#130]
Currently it is not possible to create properties of arbitrary type with null values when using the navajomap.createproperty construct.
Example:

navajomap.createproperty name="'/Apenoot/Id'" value="null"

always results in creating a "string" property Id with value null. Sometimes you want to be able to create a property with a specific type, let's say an "integer":

navajomap.createproperty name="'/Apenoot/Id'" value="null" type="'integer'"

**Comment by cbrouwer** [comment]
This seems fixed already by now. The following construction results in an integer property:
``` <navajomap.createproperty name="'/Apenoot/Id'" value="null" type="'integer'"/>```
