### ISSUE TITLE
(Tipi) (Mac) TipiTable TipiEvent onActionPerformed not triggered by Enter on a Mac

### ISSUE THREAD

**Issue by kharybdys** [Dexels/navajo#162]

**Comment by cbrouwer** [comment]
Is this still an issue?
See the KeyListener comments and implementation in TipiProperty (https://github.com/Dexels/navajo/blob/master/tipi/com.dexels.navajo.tipi.swing/src/com/dexels/navajo/tipi/components/swingimpl/TipiProperty.java line 70-140). We might be dealing with a similar issue here.

**Comment by cbrouwer** [comment]
Assuming it's fixed - reopen if not.
