### ISSUE TITLE
(Navajo) Selection property returns value when $property() in Navajo 3

### ISSUE THREAD

**Issue by kharybdys** [Dexels/navajo#223]
We noticed this morning that the behaviour of $property() has changed with respect to selection properties.
Under the old navajo, GetSelectedName($property('Sex')) worked. With Navajo 3 you get the error that the given parameter is not a selection property (almost certainly its value).
This happened inside a map.joinmessage, the example is the property SexDescription in the webservice matchreport/proxy/ProcessQueryMatchPersons.xml

Is this intended? Because then we have to replace $property by $propertyObject in all required webservices and figure out which ones they are.

**Comment by cbrouwer** [comment]
Please re-open if this is still an issue.

**Comment by kharybdys** [comment]
GetSelectedName($property('Sex')) still won't work but this has turned into the expected behaviour so the ticket can stay closed.
Use $propertyObject instead
