### ISSUE TITLE
(Tipi) Allow for union-specific validation.properties

### ISSUE THREAD

**Issue by kharybdys** [Dexels/navajo#244]
TipiAction to reload validation.properties after the login? Definitely through the CSS-like mechanism where Union-specific only needs to specify the differences from the basis validation.properties.

**Comment by cbrouwer** [comment]
I implemented a servlet which provides the validation.properties file, which can be used by all applications which would like to use it. See https://github.com/Dexels/dexels.repository/blob/master/com.dexels.resourcebundle/src/com/dexels/resourcebundle/DexelsResourceBundle.java

In the request to the servlet, the parameters determine which locale, union and possibly subunion will be served. E.g. http://server/resourcebundle?locale=nl&union=knvb&subunion=AV&resource=validation

The resources (validation is only one type of resource really) are defined here:
https://github.com/Dexels/sportlink/tree/_fb_validationproperties/resources/texts

See @roelofkemp for the reasoning for this setup and a live example.
