### ISSUE TITLE
(Navajo) Tag to throw a condition error in the same format as the usual validation errors

### ISSUE THREAD

**Issue by kharybdys** [Dexels/navajo#245]
For example, halfway through parsing the script decides that a requirement isn't fulfilled and wants to exit with a condition error exactly as if it would've come from a validation failing, so that the user interfaces responds the same.

Example: matchreport/proxy/ProcessInsertMatchPerson.
As part of needing to enter a teamPerson, information about the rest of the team is retrieved from the database. This can be used to determine whether a coach is already part of the team. If so, entering a second coach should be blocked. But if you do this through a validation check, you're doing double work. I now have a navajomap calling a webservice that has an always failing validation -> Ugly.

**Comment by DimitrisD** [comment]
Duplicate with https://github.com/Dexels/navajo/issues/457
