### ISSUE TITLE
Tipi - An executing local or globalmethod that uses executemethod seems to lose synchronization

### ISSUE THREAD

**Issue by kharybdys** [Dexels/navajo#266]
UseCase: Instantiation of the personWindow. Check with Erik or me, he was forced to use a workaround to get the desired behaviour.

**Comment by eversteeg** [comment]
Created an example in tipi branch: _fb_async_example

**Comment by cbrouwer** [comment]
The different behavior in the example was the result of the double 'ToPlainText', which caused the ShowInfo to not display some text (it resulted in invalid html text).
I updated the testcase and made it a bit more complex, but I cannot reproduce the issue so far. 

Please elaborate how to reproduce.

**Comment by kharybdys** [comment]
Cannot reproduce (anymore)
