### ISSUE TITLE
Introduce synchronized semantics in navascript

### ISSUE THREAD

**Issue by aschoneveld** [Dexels/navajo#270]
Would be nice if we can introduce atomic code blocks inside navascript.
Synchronized can be on the 'service' level or on the 'service/user' level.
```
<synchronized context="service|user">

</synchronized>
```
Introduce a cluster-wide(!) mechanism to support this, for Hazelcast:
http://docs.hazelcast.org/docs/2.0/javadoc/com/hazelcast/core/ISemaphore.html

**Comment by cbrouwer** [comment]
This has been implemented and should work.
