### ISSUE TITLE
Set textcolor of cell in tipitable 

### ISSUE THREAD

**Issue by eversteeg** [Dexels/navajo#283]
In een tipitable wil ik het mogelijk maken om een tekst in een cel van een kleur te voorzien.
Dit afhankelijk van een conditie zoals bijv. de waarde van de cel en de naam van de kolom.
Er is nu al iets dergelijks voor negatieve bedragen (type money).

**Comment by cbrouwer** [comment]
column-attribute  now takes an optional "column" in, which takes the column name this attribute applies to. Furthermore, the type="rowTextColor" can be used to alter the text color. These attributes can be used in combination with each other on the same row and/or column.

e.g.
    <column-attribute name="RowStatus" column="DateFrom" type="rowTextColor">
        <param name="concept" value="#BBBBBB" />
         <param name="passed" value="#FFAAAA" />
    </column-attribute>
