### ISSUE TITLE
(Navajo) (OSGi) Support calling tenant-specific scripts from the navajo-tester website

### ISSUE THREAD

**Issue by kharybdys** [Dexels/navajo#287]
Right now if I click a tenant specific script I get the error:
rpcName should not have a tenant suffix: matchreport/maintenance/ProcessConvertOfficialTypeToOfficialPosition_KNVB scriptName: matchreport/maintenance/ProcessConvertOfficialTypeToOfficialPosition_KNVB bare: ProcessConvertOfficialTypeToOfficialPosition_KNVB
    at com.dexels.navajo.compiler.tsl.internal.BundleCreatorComponent.getOnDemandScriptService(BundleCreatorComponent.java:721) ~[na:na]

The navajo-tester website should know to strip suffixes at the least

**Comment by cbrouwer** [comment]
For now I suggest to call the generic script from Navajo Tester. 
Automatically stripping, and after that, using the tenant of the Navajo installation could result in unexpected behavior: the script being executed might be a different one than you clicked on. E.g. you click on _KNZB, but the server actually executes the KNVB version of that script. 
Therefore automatically stripping looks like a bad idea to me.

**Comment by kharybdys** [comment]
Ok, so automatic stripping is not the solution.
But the current situation is problematic in exactly the same way.
I click on the generic script (which is empty), it executes the tenant-specific version which does have contents and therefore will execute and have effects.
Perhaps something like validating which script you want to execute - don't allow executing generic scripts if the correct tenant-specific script is available, and don't allow executing other tenant-specific scripts.

Regardless, I believe something should be changed to make this work intuitively.
