### ISSUE TITLE
Keep minimum window height and don't resize toolbar

### ISSUE THREAD

**Issue by eversteeg** [Dexels/navajo#298]
In tipi it is desirable to have a minimum height option, but more important is the option to make sure that a toolbar will never resize.
You don't want a toolbar to disappear while resizing, so the panel element should have an option to set this.

Example current code:
                    <c.panel id="toolbarPanel" constraint="South, growx" opaque="false">
                        <l.mig grid="ins 0, fillx">

Example new code:
                    <c.panel id="toolbarPanel" constraint="South, growx" opaque="false" allowresizing="false">
                        <l.mig grid="ins 0, fillx">

**Comment by eversteeg** [comment]
Current code:
                    c.panel id="toolbarPanel" constraint="South, growx" opaque="false"
                        l.mig grid="ins 0, fillx"

New code:
                    c.panel id="toolbarPanel" constraint="South, growx" opaque="false" allowresizing="false"
                        l.mig grid="ins 0, fillx"


De default should be true

**Comment by cbrouwer** [comment]
Seems to  be a MIG layout issue. Perhaps @kharybdys has an idea which constraints to use to get the desired behavior?
