### ISSUE TITLE
Don't close the overlay until the last action has been finished

### ISSUE THREAD

**Issue by eversteeg** [Dexels/navajo#300]
Example:
A tipi window has multiple localmethods with the overlay tag set,
Calling the methods one-by-one is ok, but nesting them results in removing the overlay after the first method has been finsihed.

This is just one example, but you can imagine this situation occuring in various situations.

**Comment by kharybdys** [comment]
Possible solution direction: Change the "hasOverlay" property from boolean to a counter. Every addOverlay call increases the counter (and enables the overlay if going from 0 -> 1) and every removeOverlay call decreases the counter (and disables the overlay if going from 1 -> 0).
Ofcourse you've already thought of this solution :P
