### ISSUE TITLE
mongo query with $date

### ISSUE THREAD

**Issue by roelofkemp** [Dexels/navajo#301]
When constructing a mongo query which contains a Navajo date object, like in the following example: 

    
    <param name="LastSynced">
		<expression condition="?[/Input/LastSynced]" value = "[/Input/LastSynced]" />
		<expression value="TODAY - 0#0#7#0#0#0" />
	</param>
	
	
	<map.navajomap>
		<param name="Query">
			<expression>
				<value>
					MongoTuple('To', [/Input/UserId], 'Created', MongoTuple('$gte', [/@LastSynced]))
				</value>
			</expression>
		</param>
		<navajomap.createproperty name="'/__Mongo__/Datasource'" value="'mongodwf'" />
		<navajomap.createproperty name="'/__Mongo__/Collection'" value="'MemberPortalNotifications'" />
		<navajomap.createproperty name="'/__Mongo__/Multiple'" value="true" />
		<navajomap.createproperty name="'/Mongo/Query'" value="[/@Query]" />
		<navajomap.callwebservice name="'mongo/ProcessQueryCustomMongo'" append="'/'" />
		
	</map.navajomap>

it is transformed to such a construction:

{ 'To' : 90645 , 'Created' : { '$gte' : { '$date' : '2015-05-27T07:04:54.613Z'}}}

(example)
$ use test_generic
$ db.MemberPortalNotifications.find({ 'To' : 90645 , 'Created' : { '$gte' : { '$date' : '2015-05-27T07:04:54.613Z'}}}).pretty()

which always returns zero results, whereas this construction:

{ 'To' : 90645 , 'Created' : { '$gte' : ISODate("2015-05-27T9:30:24.135Z")}}

(example)
$ use test_generic
$ db.MemberPortalNotifications.find({ 'To' : 90645 , 'Created' : { '$gte' : ISODate("2015-05-27T9:30:24.135Z")}}).pretty()

will return results.

This is most likely caused by the use of $date in a query, which apparently is not supported:
http://stackoverflow.com/questions/19819870/date-query-with-isodate-in-mongodb-doesnt-seem-to-work
http://stackoverflow.com/questions/18370206/can-strict-json-dates-be-used-in-a-mongodb-query

Possible solutions are:
1. Produce an error message in the log when such a construction is detected
2. Make sure that navajo dates in queries are transformed to ISODates rather than $dates

**Comment by cbrouwer** [comment]
Could not reproduce. Remember the toString representation of the query is not always what can be literally executed in a Mongo shell:
"That $date representation is just the toString representation in the Java driver, of a Date. It uses the strict JSON/BSON representation, rather than the extended 10gen BSON where values can be objects represented like they are in the shell."
