### ISSUE TITLE
(Navajo) (Tasks) Tasks are not deployment-independent

### ISSUE THREAD

**Issue by kharybdys** [Dexels/navajo#305]
That's because tasks define a username and password for execution, and those are not deployment-independent.

**Comment by cbrouwer** [comment]
Similar to workflows, tasks can be defined in a tenant-specific directory. Therefore I don't think this is an issue.

**Comment by kharybdys** [comment]
You're right that tasks are already tenant independent, but that doesn't necessarily make them deployment-independent. The same definition of tasks that will work on test won't necessarily work on test, due to the usage of a username and password that might not exist on both environments.

**Comment by cbrouwer** [comment]
This is now supported (with backward compatibility) using a similar syntax as in resources.xml, ie.
```
<message name="deployments">
  <message name="develop">
    <message name="tasks" type="array">
        (...)
    </message>
  </message>
  <message name="test">
    <message name="tasks" type="array">
        (...)
    </message>
  </message>
</message>
```

We still need to update all the configuration!
