### ISSUE TITLE
Cleanup WorkflowManager

### ISSUE THREAD

**Issue by cbrouwer** [Dexels/navajo#324]
The current implementation of WorkflowManager is a mix of non-OSGi and OSGi code, combined with some newly tenant-specific checks here and there. 
On a running system multiple instances of the class can be active at once (for example by running a script with a WorkflowManager map).A static volatile variable is used to keep track of the 'one true WorkflowManager', and most methods in the class use a WorkflowManager.getInstance() construction.
Some methods don't really make sense in a clustered environment. For example getWorkflows() will only return the workflows of the instance itself, rather than all activate workflows in the cluster.
All this makes for obscure code and is prone to bugs, such as #312. 

This should be cleaned up and refactored making the core more robust and play nicer in a clustered environment.

**Comment by aschoneveld** [comment]
First round of cleanup done. This can be closed for more specific issues.
