### ISSUE TITLE
(Navajo) (NTH) Compiler compiles everything starting with rpcName instead of just rpcName + tenant specific versions

### ISSUE THREAD

**Issue by kharybdys** [Dexels/navajo#327]
This means that several possibly unrelated scripts also get compiled. And that slows down the process so it'd be nicer if it wouldn't be done.

**Comment by cbrouwer** [comment]
Please clarify. Do you mean:
* abc + abc_knvb + abc_knzb

are all compiled together, or
* abc + abc_knvb + abc_knzb + abcdef + abcdef_knzb + abcdef

are compiled when calling 'abc'?

**Comment by kharybdys** [comment]
abcdef is also compiled when calling abc.
This can be seen fairly easily when calling (for example), member/ProcessQueryMember. In the log you can see it also compiles ProcessQueryMemberFunction, ProcessQueryMemberGrowth, ProcessQueryMembers and ProcessQueryMemberTeam. The only disadvantage of this example is that there aren't any union specific versions.

**Comment by cbrouwer** [comment]
Cannot reproduce. Perhaps the code changed in the mean time fixing this issue. If you can still reproduce this, re-open the issue and describe your method.
