### ISSUE TITLE
Auto compile not triggered

### ISSUE THREAD

**Issue by roelofkemp** [Dexels/navajo#332]
Today the auto compile of an included webservice was not triggered.

Let's call the included webservice A and the including webservice B

B included A with a path starting with a slash: 
```xml
<include script='/path/to/A' />
```
A was changed twice, where it did compile the first time (possibly because B was also changed, I don't know whether B changed), but it didn't the second time. The time in between was about 20 minutes.

**Comment by cbrouwer** [comment]
There have been a few fixes in the change detection of included scripts, that hopefully also fixed what caused this incident. Please re-open if you see this behavior again.
