### ISSUE TITLE
(Tipi) Reload validation.properties and start.xml on Ctrl-Z

### ISSUE THREAD

**Issue by kharybdys** [Dexels/navajo#334]
Probably through new action(s) that are then added to the current menu option for Ctrl-Z, but it's nice if changes to these files wouldn't require a restart of SLC when developing.

**Comment by cbrouwer** [comment]
Commit 2d00fda9ef55cd3fc2f5e8de66e490626c991de7 should take care of validation.properties.
Start.xml is read when creating the TipiApplication, and thus cannot be reloaded that easily. Perhaps the (existing) TipiReboot action will help?
