### ISSUE TITLE
executeMethod doesn't respect breakOnError in callService

### ISSUE THREAD

**Issue by eversteeg** [Dexels/navajo#340]
Like the title says.
When using callService and setting breakOnError=true, then the code after the executeMethod still continues.
It should, ofcourse, respect the breakOnError when a ConditionError is thrown

**Comment by cbrouwer** [comment]
Fixed in https://github.com/Dexels/navajo/commit/9b05290a3d2ecb87965e15f088f297cecf01b446 (com.dexels.navajo.tipi 2.11.0)
