### ISSUE TITLE
An Adapter to get a file from the server filesystem

### ISSUE THREAD

**Issue by kharybdys** [Dexels/navajo#344]
First response, we already have this in FileMap. But no, not entirely, as it assumes it's a textfile it's getting / the response from a FileLineMap
My usecase is for getting image(s) to then send to a BIRT. So either change FileMap to allow me to provide a path and set the contentType or some such, or a new adapter.

Or point me to the one I missed!

**Comment by kharybdys** [comment]
TemplateMap also doesn't work as it assumes it needs to parse and having "["'s in a non-text file is definitely possible.

**Comment by cbrouwer** [comment]
The function ToBinaryFromPath() might be of help?
Either way I would prefer for as little filesystem interaction during runtime as possible, so therefore I'm closing this issue.
