### ISSUE TITLE
(MailMap) Support relatedMultipart per attachment

### ISSUE THREAD

**Issue by kharybdys** [Dexels/navajo#346]
Due to two unions' complaints, we probably want support for relatedMultipart per attachment in the MailMap.
Use case that goes wrong:
Mail is sent with three attachments (1, 2, 3). 1 and 2 (icons) are inline attachments and are referred to from the body. 3 is a wholely separate attachment. With the current flag "relatedMultipart", you can set the entire set of attachments to use multipart/related instead of multipart/mixed, but iOS (and the new KNZB webclient) can't handle this case when it's multipart/related.
When setting the entire set of attachments to multipart/mixed, the inline attachments show up as separate attachments and no longer in the body.
Preference is to be able to have support for both inline and non-inline attachments in the same email. Either by setting the flag per attachment or allowing two lists of attachments to be specified or a better idea.

**Comment by kharybdys** [comment]
http://helpdeskbond.sportlinkservices.com/ozh16bond/supporter/?t=tupd&id=20575

**Comment by kharybdys** [comment]
http://helpdeskbond.sportlinkservices.com/ozh16bond/supporter/?t=tupd&id=20688

Ticket waarin de KNZB meldt dat hetzelfde probleem speelt bij hun nieuwe webclient en de tuchtmails.

**Comment by cbrouwer** [comment]
Use the CommonsMailMap for these type of emails - it will work out the required multipart headers itself without further issues.
