### ISSUE TITLE
change implementation of removeDuplicates to be based on equals() rather than hashcode()

### ISSUE THREAD

**Issue by roelofkemp** [Dexels/navajo#361]
The removeDuplicates property of a message map uses the hashcode function to compute a hashcode for each message (the sum of the hashcodes of the string values of the properties) to remove duplicates from an array.

This results in unexpected behavior where for two different messages the same hashcode is generated and one of them is falsely removed.

As discussed with Frank the implementation could also use the equals method, so that difference in one property cannot be compensated by another property. Also an implementation with equals will check whether the property names match, in the current implementation only the values of the properties are considered, so two messages with different property names, but equal values will be given the same hashcode.

related to this issue: http://helpdesk.sportlinkservices.com/ozh16club/supporter/index.php?t=tupd&id=69052

**Comment by cbrouwer** [comment]
I agree with the shortcomings of the current removeDuplicates implementation. 
The equals() implementation should check:

- message name and type
- number of properties and submessages;
- for each property, check name, type and value;
- call this check function for each submessage recursively.

Do we need to check existing webservices when updating the behavior of removeDuplicates?

**Comment by roelofkemp** [comment]
We did, there are hardly any webservices using it. For all existing webservices it is fine to change the behavior

**Comment by cbrouwer** [comment]
Some questions that arise:

- must the (top)message name be equal for two messages to be considered equal?
- how should array messages be compared? Should the order of the elements be equal for the message to be considered equal? I would say no, but this does make the calculation quite expensive.

**Comment by roelofkemp** [comment]
as far as I know 'remove duplicates' is used on array messages. So it operates on elements of an array message, and top message name will always be the same. But for completeness, I'd say please check those names too. 

And of course the indices of the array messages will differ but this shouldn't make two otherwise equal message inequal. So please don't include the index (order) of the array element message in the check.
