### ISSUE TITLE
Using < or > in quoted string value, causes compile error in include file 

### ISSUE THREAD

**Issue by eversteeg** [Dexels/navajo#362]
Example:
<expression value="[/@Param1] + '<br/>' + [/@EmailAddress] + ' whatever '"/>

In a normal webservice this is no problem, but when in an include file.... compile error

**Comment by eversteeg** [comment]
Example:

`<expression value="[/@Param1] + '<br/>' + [/@EmailAddress] + ' whatever '"/>`

This line is ok in a normal webservice, but not ok in an include file

**Comment by DimitrisD** [comment]
This issue cannot be easily solved. It demands a use of different external libraries for xml parsing, something which at the moment is not happening.

Instead, you can have the same functionality using the appropriate html character encodings for the signs:

`&apos;&lt;&apos;     for    <`
`&apos;&gt;&apos;    for     >`

eg

```xml
<expression value="'Test '+ &apos;&lt;&apos;  + 'br/' +  &apos;&gt;&apos; + [/@EmailAddress] + ' whatever '"/>
```
