### ISSUE TITLE
Writing a null value into a property shouldn't change its type

### ISSUE THREAD

**Issue by kharybdys** [Dexels/navajo#364]
Say you have an existing property of type integer, and you are (over)writing its value with null, then it shouldn't change the type of the property as null is of all types.
It changes it to string right now, which is a fair default if the type is not known.

**Comment by cbrouwer** [comment]
A property defined as 
```<property name="aaa" type="integer" value="null">``` 

results in the following property when running:
```      <property name="aaa" type="integer" value="null" direction=""/> ```

Thus this seems to be the desired behavior?

**Comment by kharybdys** [comment]
Nevermind, problem wasn't this but forgot to specify type of property.
