### ISSUE TITLE
Tasks with same name firing at same time on same application server for different tenants don't all complete

### ISSUE THREAD

**Issue by kharybdys** [Dexels/navajo#367]
Found this out while testing whether #304 was indeed fixed (it was), see log in comment and example in branch _fb_navajoissue_367.

**Comment by kharybdys** [comment]
TestTaskCompilation has a generic version and a KNKV version (both with a single debug statement in them). They were defined in tasks.xml to trigger at 12 minutes past every hour for both NHV as well as KNKV. In the log you can see that they both trigger at 15:12 both only one executes (the NHV one). Then at 15:30 a different trigger triggers and the KNKV 15:12 finally executes.


15:12:00.117 INFO  c.d.n.scheduler.triggers.TimeTrigger - TestTaskCompilation time:*|*|*|12|*: Firing for a trigger that ran at: -1, that was: 1464268320118 millis ago.
15:12:00.118 INFO  c.d.n.scheduler.triggers.TimeTrigger - TestTaskCompilation time:*|*|*|12|*: Now rest to: 1464268320118, that is: 0 millis ago.
15:12:00.118 INFO  c.d.n.scheduler.triggers.TimeTrigger - TestTaskCompilation time:*|*|*|12|*: Firing for a trigger that ran at: -1, that was: 1464268320119 millis ago.
15:12:00.118 INFO  c.d.n.scheduler.triggers.TimeTrigger - TestTaskCompilation time:*|*|*|12|*: Now rest to: 1464268320118, that is: 0 millis ago.
15:12:00.119 DEBUG c.d.n.scheduler.triggers.Trigger - Performing trigger: time:*|*|*|12|*. taskid=TestTaskCompilation,webservice=TestTaskCompilation,workflow=null,workflowid=null
15:12:00,141 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.FileAppender]
15:12:00,141 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [NavajoFile-C:\Marte\Git\sportlink]
15:12:00,144 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
15:12:00,145 |-INFO in ch.qos.logback.core.FileAppender[NavajoFile-C:\Marte\Git\sportlink] - File property is set to [C:\Marte\Git\sportlink/logs/rpc/TestTaskCompilation.log]
15:12:00,147 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.FileAppender]
15:12:00,147 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [NavajoFile-C:\Marte\Git\sportlink]
15:12:00,147 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
15:12:00,147 |-INFO in ch.qos.logback.core.FileAppender[NavajoFile-C:\Marte\Git\sportlink] - File property is set to [C:\Marte\Git\sportlink/logs/user/ROOT.log]
15:12:00.141 INFO  NavajoLog - CACHE EENTRY: serviceName=team/ProcessGetStatisticsPerTeamPerson,serviceKey=/TeamStatistics/TeamId,/TeamStatistics/SeasonId,/TeamStatistics/DisciplineType,persistenceKey=,expirationInterval=1200000
15:12:00.149 INFO  NavajoLog - Started Cache Controller Reader
15:12:00.173 INFO  c.d.n.p.impl.PersistenceManagerImpl - ============================================================================
15:12:00.173 INFO  c.d.n.p.impl.PersistenceManagerImpl - inMemoryCache = {}
15:12:00.173 INFO  c.d.n.p.impl.PersistenceManagerImpl - accessFrequency = {}
15:12:00.173 INFO  c.d.n.p.impl.PersistenceManagerImpl - sharedPersistenceStore = com.dexels.navajo.mongo.sharedstore.MongoSharedStore@64445114
15:12:00.173 INFO  c.d.n.p.impl.PersistenceManagerImpl - ============================================================================
15:12:00.174 INFO  c.d.n.c.t.i.BundleCreatorComponent - No known extension for TestTaskCompilation - determined .xml as script extension!
15:12:00.210 DEBUG c.d.n.mapping.compiler.TslCompiler - Getting script: /TestTaskCompilation
15:12:00.329 WARN  c.d.n.c.t.i.JavaCompilerComponent - Creating compiledScript for default package!
15:12:00.859 WARN  c.d.n.c.t.i.JavaCompilerComponent - Creating compiledScript for default package!
15:12:01.090 INFO  c.d.n.c.t.i.BundleCreatorComponent - Finished compiling and bundling TestTaskCompilation
15:12:01.095 DEBUG c.d.n.mapping.compiler.TslCompiler - Getting script: /TestTaskCompilation_KNKV
15:12:01.112 WARN  c.d.n.c.t.i.JavaCompilerComponent - Creating compiledScript for default package!
15:12:01.364 WARN  c.d.n.c.t.i.JavaCompilerComponent - Creating compiledScript for default package!
15:12:01.624 INFO  c.d.n.c.t.i.BundleCreatorComponent - Finished compiling and bundling TestTaskCompilation_KNKV
15:12:01.626 DEBUG c.d.n.c.t.i.BundleCreatorComponent - Installing script: TestTaskCompilation_KNKV.jar
15:12:01.632 INFO  n.script.TestTaskCompilation|KNKV - BundleEvent INSTALLED
15:12:01.637 INFO  n.script.TestTaskCompilation|KNKV - BundleEvent RESOLVED
15:12:01.643 INFO  n.script.TestTaskCompilation|KNKV - ServiceEvent REGISTERED
15:12:01.647 INFO  n.script.TestTaskCompilation|KNKV - BundleEvent STARTED
15:12:01.647 DEBUG c.d.n.c.t.i.BundleCreatorComponent - Installing script: TestTaskCompilation.jar
15:12:01.653 INFO  navajo.script.TestTaskCompilation - BundleEvent INSTALLED
15:12:01.656 INFO  navajo.script.TestTaskCompilation - BundleEvent RESOLVED
15:12:01.660 INFO  navajo.script.TestTaskCompilation - ServiceEvent REGISTERED
15:12:01.661 DEBUG c.d.n.c.t.i.BundleCreatorComponent - Finished on demand compiling of: TestTaskCompilation
15:12:01.661 INFO  navajo.script.TestTaskCompilation - BundleEvent STARTED
15:12:01.676 INFO  com.dexels.navajo.script.api.Access - DEBUG: This is the generic TestTaskCompilation script
 --------- BEGIN NAVAJO CONSOLE OUTPUT ---------
DEBUG: This is the generic TestTaskCompilation script
--------- END NAVAJO CONSOLE OUTPUT ---------
15:30:00.443 INFO  c.d.n.scheduler.triggers.TimeTrigger - sendmailalerts time:*|*|15|30|*: Firing for a trigger that ran at: -1, that was: 1464269400444 millis ago.
15:30:00.443 INFO  c.d.n.scheduler.triggers.TimeTrigger - sendmailalerts time:*|*|15|30|*: Now rest to: 1464269400443, that is: 0 millis ago.
15:30:00.443 DEBUG c.d.n.scheduler.triggers.Trigger - Performing trigger: time:*|*|*|12|*. taskid=TestTaskCompilation,webservice=TestTaskCompilation,workflow=null,workflowid=null
15:30:00.444 DEBUG c.d.n.scheduler.triggers.Trigger - Performing trigger: time:*|*|15|30|*. taskid=sendmailalerts,webservice=alert/ProcessSendAlerts,workflow=null,workflowid=null
15:30:00,447 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.FileAppender]
15:30:00,448 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [NavajoFile-C:\Marte\Git\sportlink]
15:30:00,450 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
15:30:00,450 |-INFO in ch.qos.logback.core.FileAppender[NavajoFile-C:\Marte\Git\sportlink] - File property is set to [C:\Marte\Git\sportlink/logs/rpc/alert/ProcessSendAlerts.log]
15:30:00,702 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.FileAppender]
15:30:00,702 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [NavajoFile-C:\Marte\Git\sportlink]
15:30:00,703 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
15:30:00,703 |-INFO in ch.qos.logback.core.FileAppender[NavajoFile-C:\Marte\Git\sportlink] - File property is set to [C:\Marte\Git\sportlink/logs/user/R3OT.log]
15:30:00.446 INFO  c.d.n.c.t.i.BundleCreatorComponent - No known extension for alert/ProcessSendAlerts - determined .xml as script extension!
15:30:00.450 INFO  com.dexels.navajo.script.api.Access - DEBUG: This is the KNKV TestTaskCompilation script
 --------- BEGIN NAVAJO CONSOLE OUTPUT ---------
DEBUG: This is the KNKV TestTaskCompilation script
--------- END NAVAJO CONSOLE OUTPUT ---------
15:30:00.874 DEBUG c.d.n.mapping.compiler.TslCompiler - Getting script: alert/ProcessSendAlerts
15:30:01.758 INFO  c.d.n.c.t.i.BundleCreatorComponent - Finished compiling and bundling alert/ProcessSendAlerts

**Comment by kharybdys** [comment]
Note that the sendmailalerts task is configured to trigger at 15:30 for KNKV and 15:31 for NHV - suggesting this is a known "feature"

**Comment by kharybdys** [comment]
Feature branch with testcase is available

**Comment by cbrouwer** [comment]
I am unable to reproduce the issue:
```
07:58:01.828 INFO  com.dexels.navajo.script.api.Access - DEBUG: This is the KNKV TestTaskCompilation script
 --------- BEGIN NAVAJO CONSOLE OUTPUT ---------
DEBUG: This is the KNKV TestTaskCompilation script
07:58:01.828 INFO  com.dexels.navajo.script.api.Access - DEBUG: This is the generic TestTaskCompilation script
--------- END NAVAJO CONSOLE OUTPUT ---------
 --------- BEGIN NAVAJO CONSOLE OUTPUT ---------
DEBUG: This is the generic TestTaskCompilation script
--------- END NAVAJO CONSOLE OUTPUT ---------
```

Is it possible the Navajo server wasn't fully started up yet?

**Comment by kharybdys** [comment]
Agreed, cannot reproduce (anymore). But it won't have been because the server wasn't fully started up yet.
