### ISSUE TITLE
get rid of block="false" in navajomap.callwebservice

### ISSUE THREAD

**Issue by roelofkemp** [Dexels/navajo#370]
We have multiple ways to start a webservice asynchronously after the completion of another webservice.

Option 1: define a task/workflow with a webservice trigger
Option 2: do a navajomap.callwebservice with property block="false"

I'd like to have just one option, to keep navajo simple and avoid style differences between programmers. Therefore, I think it's good (examine if it is possible) to get rid of option 2 and only support option 1.

Arguments for option 1 are:
- more aspect oriented, let pieces of code do exactly what they should do (e.g. ProcessUpdateSomething will only update and not do something else, the something else will be started upon the trigger)

And for option 2:
- more explicit, when you read the script it is easier to detect that something else is linked to the script
- async webservices can be started during the execution of the script, not only at completion time.

**Comment by cbrouwer** [comment]
One use-case for the non-blocking navajomap construction is where you need control over the input document.
Take for example a situation where you loop over a resultset. For each result you construct a message and use a navajomap to call another webservice. The latter can sometimes be done asynchronous, using block="false".

To get this use-case to work without non-blocking navajomap, it becomes a bit tricky. One could possibly keep the navajomap, but remove all implementation. Then define a workflow/trigger on that webservice, which calls the actual implementation script in an asynchronous way.

However, this is quite a bit more complex and obfuscates what's actually happening. Thus, it seems to be there are some use-cases where the non-blocking navajomap is legitimate and preferable.
