### ISSUE TITLE
(Tipi) Possibility to signify on a webservice call that is has to succeed before the application may continue

### ISSUE THREAD

**Issue by kharybdys** [Dexels/navajo#375]
At the startup of SLC (and other tipi applications), several webservice calls are so critical that they cannot fail due to eg network problems. Make a way in which we can signify which webservice these are and make sure these retry until they succesfully complete.

**Comment by cbrouwer** [comment]
Could this not be handled by the onError event on the callService? Something like:
```
<callService service="'example/service'">
    <onError>
        (show error dialog explaining application is going to be closed)
        <exit />
    </onError>
</callService>
```

**Comment by cbrouwer** [comment]
Obviously I missed the retry part.

In https://github.com/Dexels/navajo/commit/fb604213a9b9c8f753be3893b28563b92ca0432c it's now possible to pass a "retries" parameter to callService, e.g. ``` <callService service="'example/service'" retries="5">```. 

To prevent bursts of requests retries, I added a simple backoff algorithm, basically: (nr_of_exceptions * 1.5s) sleep between retries. 

I suggest to use this in combination with the onError, when dealing with webservices so important to the application that it should close if (repeated) requests fail.
