### ISSUE TITLE
(Navajo) Possibility for validation checks to be able to define intermediate results (params?)

### ISSUE THREAD

**Issue by kharybdys** [Dexels/navajo#381]
Validation checks often become almost unreadable because they need to be self-contained and thus require lots of repetition ("if A is not null and A is false then" becomes ugly when A is a SingleValueQuery or similar).
It would be cool if a single check, or the entire validations tag, could have an area which defines intermediate results which can then be referenced from the validation check(s).

No clue what the best way to do this would be, though.

**Comment by kharybdys** [comment]
Standard problem with anything happening before the validations is that your input hasn't been validated yet.
Perhaps a more valid option is to be able to define delayed validations. So that you can have your simple input validations fire directly, then do a bit of calculation, then insert a tag that says "now fire this group of delayed validations". Being able to define multiple groups could be interesting too.

**Comment by kharybdys** [comment]
Just talked to Erik and the question is whether I'm not overcomplicating things. There is a CallService navajo function that evaluates a given expression on the result of a webservice call given the same input as the current webservice. This might be a sufficient solution.

**Comment by cbrouwer** [comment]
Another option might be to define the params, and then perform a NavajoMap to a 'validation service', which only performs validation checks given the defined params.
Closing the issue due to the available alternatives.
