### ISSUE TITLE
(Navajo) Possibility for filters to define local variables before checking the filter

### ISSUE THREAD

**Issue by kharybdys** [Dexels/navajo#382]
Similar to validations (#381), filters are often enough complex things with repetition as they need to be self-contained. If filter checking could become a two step process, with step one calculation and step two the check itself, that would go a long way towards making these more readable.

An extra complication is that the filter (check) is often using a define right now. In the interest of having related code near each other, it would be extra cool if the calculation steps could also use the define construction.

**Comment by cbrouwer** [comment]
Currently I feel the cons (added complexity to Navajo and to the scripting engine) do not outweigh the pros.

There are now roughly 1400 scripts in Sportlink with a filter defined somewhere. Out of those 1400 there are 50 scripts with a long/complex filter (of around 200 characters or longer). Even for those 50, I doubt separation would be useful in all. I am sure there will be a few cases where it will be useful and make the script more readable, but given the limited possible usage I feel this does not outweigh the cons. Thus for now I will close this issue.
