### ISSUE TITLE
Problem with AsyncClient

### ISSUE THREAD

**Issue by kharybdys** [Dexels/navajo#385]
I made two scripts that consistently trigger this error on my platform (Windows).
See branch _fb_navajoissue_385

It does assume you are working against the Sportlink development databases

**Comment by kharybdys** [comment]
Conclusion is that the call never reaches the server and goes timeout after five minutes. However, the server then continues with after run as if the script succesfully completed, resulting in the NPE that is the symptom of this problem.

Also, if I jump from locally to test, I get the same five minutes & NPE, if I jump from test to another server on test, no problems.

**Comment by kharybdys** [comment]
Important, calling birt from local does work. However this uses the "resource" construction instead of the "server" construction

**Comment by cbrouwer** [comment]
There has been a small bugfix recently where a async client was closed too soon. Can you check if this perhaps also fixed this issue?

**Comment by kharybdys** [comment]
Seems it has been fixed. I at least cannot reproduce anymore
