### ISSUE TITLE
NavajoMap append semantics have changed

### ISSUE THREAD

**Issue by aschoneveld** [Dexels/navajo#386]
When using following construction

`<navajomap.callwebservice name="'mongo/ProcessAggregateMongo'" append="''" />`

The behaviour should be that the entire output doc/response from the called webservice will become the output doc of the callee. 

With latest version this does not happen.

There seems to be an issue here (used to work) in NavajoMap.java (line 287):

` if (messageOffset.equals("")) {
        	inDoc.write(System.err);
            access.setOutputDoc(inDoc);
            return;
        }`

**Comment by cbrouwer** [comment]
I am not able to reproduce this bug.

Consider two simple scripts. InitHello.xml: 
```
<navascript>
	<message name="HelloData">
		<property name="Greeting" direction="out">
			<expression value="'Hello ' + [/@NavajoUser]" />
		</property>
	</message>
	<map.navajomap>
		<navajomap.callwebservice name="'InitHello2'" append="''" />
	</map.navajomap>
</navascript>
```

and InitHello2.xml:
```
<tsl>
  <message name="HelloData2">
    <property name="Greeting2" direction="out">
      <expression value="'Hello ' + [/@NavajoUser]"/>
    </property>
  </message>
</tsl>
```

The result of calling InitHello is:
```
<tml documentImplementation="SAXP">
   <message name="HelloData2">
      <property name="Greeting2" type="string" value="Hello ROOT" direction="out"/>
   </message>
   <methods/>
   <operations/>
</tml>
```

Can you make a reproducible testcase?

**Comment by aschoneveld** [comment]
I noticed that it only happens when you add a <break/> inside the script.

**Comment by cbrouwer** [comment]
Can you elaborate (add a what?) or make a small testcase?

**Comment by aschoneveld** [comment]
Haha, I added: <break/>
But you cannot see that.... again 'as code': `</break>`
Already changed it in my previous comment.
