### ISSUE TITLE
Default MessageName/Collection should be Entity name in GET

### ISSUE THREAD

**Issue by aschoneveld** [Dexels/navajo#387]
When defining a GET operation using mongo/ProcessQueryMongo is it is currently needed that MessageName is defined. For PUT/POST this is not the case. Also for a GET MessageName should be optional and by default be set to the name of the entity.

**Comment by cbrouwer** [comment]
I checked and confirmed this is working for all methods, using the operations that call the mongo/ scripts directly. When using a different script (that in turn uses a NavajoMap to call a mongo/ script) one must obviously still pass these values (that can be defined in the entity or in the script itself).
If we do still encounter a situation where this does not work as expected, this issue can be reopened.
