### ISSUE TITLE
copymessage generates weird messages

### ISSUE THREAD

**Issue by roelofkemp** [Dexels/navajo#391]
`<map.copymessage copyMessageTo="'/Notification/Attributes'" useOutputDoc="false" copyMessageFrom="'/Notification/Attributes'" />`

results in message with name "Notification/Attributes" instead of message "Notification" with submessage "Attributes" as long as no message with name "Notification" exists in the out doc.

**Comment by kharybdys** [comment]
Constructions with ''' <message name="../Bla"> ''' are now also blocked. These should still be possible

**Comment by cbrouwer** [comment]
I cannot reproduce this error. The following construct still works. Can you give me a concrete example?
```
<message name="HelloData">
   <message name="../Bla" />
</message>
```

**Comment by DimitrisD** [comment]
Is this relevant? When I try to reproduce i get this:
![image](https://user-images.githubusercontent.com/6371095/41645119-4cbcd8ea-7470-11e8-9155-808dc1af6f46.png)

**Comment by DimitrisD** [comment]
After discussion with @roelofkemp this functionality is not needed, and if needed it has a workaround (create the message and copy the submessage) and there is an explanatory error message, so this is resolved.
