### ISSUE TITLE
CSVMap's maximumImportCount does one more than defined

### ISSUE THREAD

**Issue by kharybdys** [Dexels/navajo#392]
Due to lineCount being 0-based while maximumImportCount is 1-based, if you define a maximum of 1, you get two lines returned (etc etc).
Please fix.

**Comment by cbrouwer** [comment]
The difference wasn't really a result of 0 or 1 based, but instead it seems the logic assumed the  `skipFirstRow` option would always be true. 
I changed the logic a bit, which should now return the correct amount of lines regardless of the  `skipFirstRow` option. Please test the new version.
