### ISSUE TITLE
Entity get + append and field construction

### ISSUE THREAD

**Issue by eversteeg** [Dexels/navajo#400]
There seems to be a bug in the navajo append/appendTo construction.
The commented code below is much cleaner and works, but you can not use a condition on append.
Therefor used the field construction, but then..... the append doesn't work as expected.

Check memberportal/internal/favorites/ProcessSearchFavoritePersonId for further info

**Comment by cbrouwer** [comment]
I am not quite sure what exactly the 'bug' is here.

As for the problem, something like this seems to work:
```
<map.entity name="'PersonEntiy">
        <entity.createproperty name="'PersonId'" value="'aap'" />
        
        <entity.get  appendTo="'/Person/'" />
        <field name="append" condition="$exists('/PersonBasic/PrivacyLevel') AND $property('/PersonBasic/PrivacyLevel') != 'PRIVATE' " >
            <expression value="'/PersonBasic'" />
        </field>
    </map.entity>
```

**Comment by eversteeg** [comment]
Seems to be the same problem as issue 404. Which can be deducted to "not knowing" all the ins and outs of navajo. ;-)
Changed the code in the webservice to match the given example (sort of) and it does the trick.

**Comment by cbrouwer** [comment]
Note that the 'append' should also be possible to use as a navascript field, ie. `<entity.append>` once this is added in the navascript definition. That should eliminate the need for `<field>`
