### ISSUE TITLE
Appending array message within loop to '.'

### ISSUE THREAD

**Issue by eversteeg** [Dexels/navajo#404]
While looping over an arraymessage (from a navajomap call), you might want to cal another navajomap which returns an array by itself.
Normally you would append the output of a navajomap call to the array element by using appendTo="'.'".
That option doesn't work when you want to add an array message. The last entry of the array will be appended, but the other entries are lost.

**Comment by eversteeg** [comment]
See external/mongo/my/ProcessQueryMyTeams (line 250).
Concerns the navajomap call to external/mongo/my/internal/ProcessQueryTeamPersonData

**Comment by cbrouwer** [comment]
If the appendTo logic ends with a "/", the entire message is appended. If not, it is merged with the current message. Thus appendTo is a "."  and the message is an array message, this causes some weird results... When using "./", the full array message is kept.
