### ISSUE TITLE
timestamp and date data types in combination with Mongo and Entities

### ISSUE THREAD

**Issue by roelofkemp** [Dexels/navajo#405]
Navajo supports both navajo and date data types, where both data types can also contain time (hours, minutes, etc).

A Mongo ISODate can also contain time, and is --after querying--  automatically  converted to a Navajo date. When this is used in combination with entities, the resulting entity will convert the Navajo date to JSON and thereby looses the time. Setting the property type to 'timestamp' instead of 'date' won't help, since the actual value from the query will be the result value.

Easy fix would be to change the Navajo to JSON conversion for dates to include timestamp, however this very likely would break existing APIs to third parties and thus has to be done carefully.

**Comment by cbrouwer** [comment]
The `timestamp` property type was created specifically for this purpose. Could you clarify this part, perhaps with an example? 
> Setting the property type to 'timestamp' instead of 'date' won't help, since the actual value from the query will be the result value.
