### ISSUE TITLE
Introduce a property type for Coordinates

### ISSUE THREAD

**Issue by cbrouwer** [Dexels/navajo#409]
Currently coordinates are usually processed as separate properties. For example: 
```xml
 <message name="Result">
        <property name="Latitude" direction="out">
            <expression value="5.75587530066031"/>
        </property>
        <property name="Longitude" direction="out">
            <expression value="53.2667609381942"/>
        </property>
  </message>
```
Although this is not wrong, conceptually these fields belong together - one is useless without the other, thus using separate properties is not ideal.

We might consider introducing a dedicated Navajo datatype for them, which would allow them to be seen as 1 entity, enabling (or simplying) various processing steps on the coordinates.
For example, it would allow us to store the coordinates as actual coordinates in MongoDB (instead of two float fields), which would make it possible to use [Geospatial indexes](https://docs.mongodb.com/manual/applications/geospatial-indexes/), with features such as $near, $minDistance and $maxDistanc.

The [GeoJON](http://geojson.org/) format could be worth looking at.

**Comment by DimitrisD** [comment]
On navajo release 3.6.7. Code on test.
