### ISSUE TITLE
(Workflow) Beforenavajo trigger not blocking

### ISSUE THREAD

**Issue by kharybdys** [Dexels/navajo#410]
In the ELO project I'm trying to use a beforenavajo trigger to query the value of a field before the triggering script updates it. However, the triggering script is not blocked, despite having `forcesync="true"` on the task.

Example is _fb_rfc841_knvb_elo 
The workflow is notifyELO, it's about the trigger on course/ProcessUpdateActivityStatus. You can use the following input for this webservice:
```
   <message name="ActivityUpdateData" type="">
      <property length="25" name="ActivityId" type="integer" value="10613110" direction="in"/>
      <property length="25" name="Status" type="string" value="PLANNED" direction="in"/>
   </message> 
```
There's a debug tag in ProcessUpdateActivityStatus which you see first: 
`DEBUG: Updating status to: PLANNED`
And then two lines from external/knvb/elo/notify/ProcessUpdateCourseStatus
`
DEBUG: Original status is: PLANNED
DEBUG: ELO StatusId is: 
`

**Comment by cbrouwer** [comment]
Removing `transient="true"` in the workflow fixes this.
