### ISSUE TITLE
(Copymessage map) Copying an array element to a new message does not change its type

### ISSUE THREAD

**Issue by kharybdys** [Dexels/navajo#411]
Code like
`
        <map.copymessage copyMessageTo="'/Participant'" useOutputDoc="true" copyMessageFrom="'/Participants@0'"/>
`
behaves differently depending on the existence of a message `Participant` in the outdoc already. If it exists, the message is appended there. Otherwise a new message `Participant` is created but it is still type `array_element` with an index attribute. This does not make sense to me, it should retype to `simple`.

I understand that the message type is hardly important, but it still irks me

Full test setup:

```
<navascript debug="response">
    <message name="Participants" type="array">
        <message name="Participants" type="array_element">
            <property name="PersonId" type="string" value="Test"/>
        </message>
    </message>
<!--     <message name="Participant"/> -->
        <map.copymessage copyMessageTo="'/Participant'" useOutputDoc="true" copyMessageFrom="'/Participants@0'"/>

</navascript>
```
See the difference when the middle bit is commented and when it isn't

**Comment by DimitrisD** [comment]
Located the issue. Implemented the solution and now creating test cases.
