### ISSUE TITLE
(Entity) Error out when a (required) input property doesn't conform to defined format

### ISSUE THREAD

**Issue by kharybdys** [Dexels/navajo#416]
Eg when defining a date property, providing "aap" as input should error out.
Same with integer property. Etc.
Is necessary I think for required properties (and/or the required validation needs to take place AFTER the parsing), but might be a good idea for any input property

**Comment by DimitrisD** [comment]
I have a proposal for this one.

The class com.dexels.navajo.document.Property contains a very valuable function that can make our lives easier:

**property.getTypedValue()**

We can use this function to create a validation method.

In this validation method, we will check whether the value of the property is empty ("") or not. If it's not empty we will call the getTypedValue() method. This method will return either a null object (if the conditions of type and value are not consistent) or typed object.

If it's not null the null object, we will check the type of the object, and if that type is the same as the type of the property that the entity requires, the the validation will be marked as successful.

In any other case it's unsuccessful.

Here is a draft of the code:

![image](https://user-images.githubusercontent.com/6371095/36036678-c3c12a30-0dba-11e8-9295-5647dc3ca25d.png)

**Comment by DimitrisD** [comment]
@cbrouwer we should close this as well.
