### ISSUE TITLE
Message orderby gets lost when using Navajo Maps

### ISSUE THREAD

**Issue by flyaruu** [Dexels/navajo#418]
It is known that the message orderby only gets performed when the message is being serialized, so when using an internal navajomap the orderby does not do anything.

But this does not explain that when appending a navajomap result to the outdoc, the 'orderby' attribute gets lost. 

If the orderby attribute would still be there, the orderby would be performed when the message when the Navajo object finally gets serialized.

If we fix that, it will remove the need of most performOrderBy calls, and make the use orderby more intuitive.

**Comment by flyaruu** [comment]
@roelofkemp

**Comment by eversteeg** [comment]
This issue is not solved.
Calling webservice B, where a orderby tag is placed on the outputmessage, loses the orderby in the parent webservice A.
An explicit performOrderBy is necessary to (re)trigger the ordering.
