### ISSUE TITLE
(Tipi) Menu accelerators work when the menuitem is hidden

### ISSUE THREAD

**Issue by kharybdys** [Dexels/navajo#421]
Not sure this is something we can fix but it shouldn't be the case anyhow.

**Comment by DimitrisD** [comment]
I don't think that this is something we can fix 

The code above is from the class JMenuItem which is inherited by the TipiSwingMenuItem: 
![image](https://user-images.githubusercontent.com/6371095/36541460-42d96274-17de-11e8-9b55-98b5967f0a2f.png)

While the menu exists, whether the menu item is hidden or not, the accelerator is there ready to listen.

Any thoughts on this would be valuable.

**Comment by cbrouwer** [comment]
Can we unset the accelerator (perhaps with setAccelerator(null) or something) of the menu item when disabling/hiding the menu item?

**Comment by DimitrisD** [comment]
That's what i'm currently trying to figure out. Whether we can just call the the setAccelerator with other arguments.
