### ISSUE TITLE
(NavajoMap) Support for creating array elements does not extend to sub-arrays

### ISSUE THREAD

**Issue by kharybdys** [Dexels/navajo#422]
See the following snippet:
```
<?xml version="1.0" encoding="UTF-8"?>
<navascript>
    <map.navajomap>
        <navajomap.createproperty name="'/Transaction/PrimaryKey@0/Name'" value="'matchid'"/>
        <navajomap.createproperty name="'/Transaction/PrimaryKey@0/Value'" value="87243"/>
        <navajomap.callwebservice name="'InitTest'"/>
    </map.navajomap>
</navascript>
```
This creates the error: "Can only create array elements inside array message"
Preliminary research suggests this is because the support for creating array messages in this way only works on toplevel.

**Comment by DimitrisD** [comment]
The issue exists at the function MappingUtils.getMessageObject.
Still investigating.
