### ISSUE TITLE
scala webservice inheritance support 

### ISSUE THREAD

**Issue by ghost** [Dexels/navajo#426]
check if scala webservices can support inheritance and or supporting class dependancies

**Comment by cbrouwer** [comment]
Scala script files can now reference common logic in root:/scalacommon. All files in this directory will be taken into account when compiling a scala script, allowing to store common logic in a centralized place.

Do note that the life-cycle of these files is different than that of regular (scala) scripts. Changes in scalacommon will not be picked up runtime (but instead require a restart).
