### ISSUE TITLE
(Tipi) Internationalization needed for TipiShowQuestion, TipiShowInfo, TipiShowWarning and TipiShowError

### ISSUE THREAD

**Issue by kharybdys** [Dexels/navajo#430]
Especially TipiShowQuestion has hardcoded Dutch in the java code. It needs to be properly internationalized. How, I don't have a ready answer for.
Once that's done, the other three should be checked for missing internationalization as well.

**Comment by kharybdys** [comment]
This needs to happen for at least the Vaadin and Swing Tipi implementations, but perhaps for all?

**Comment by kharybdys** [comment]
Might need to check the entirety of tipi, just found another hardcoded Dutch string intended for display in TipiBaseQuestion

**Comment by cbrouwer** [comment]
As per the commit, I decided to use the existing Lookup functionality for this. It will be slightly less efficient, but it prevents having to keep track of yet another location for translated strings.

**Comment by DimitrisD** [comment]
duplicate #434
