### ISSUE TITLE
(Tipi) (Tipitable) When the property of the first row of a column is not editable in a column of boolean values, the column header's event isn't fired

### ISSUE THREAD

**Issue by DimitrisD** [Dexels/navajo#431]
When the property of the first row of a column is not not editable (direction="in"), for a column that has boolean properties (select boxes), then that column header's right click event is not fired (the menu is not shown on right click).

Example for testing : in repo **com.sportlink.club**  and branch **_fb_bugfixes_erik**, script testTipiTableSorting.xml long with ProcessTestTableSorting.xml.

**Comment by cbrouwer** [comment]
Could this perhaps be caused by a missing definition message?

**Comment by DimitrisD** [comment]
Nope. Added the definition message and it's persistent.
