### ISSUE TITLE
(Tester) Memo property doesn't work

### ISSUE THREAD

**Issue by kharybdys** [Dexels/navajo#437]
I made an input script with a property type memo and it displayed correctly as a textfield. But after having pasted in a block of text and using method to call another script, the contents of my paste didn't arrive at the other script

**Comment by DimitrisD** [comment]
Can you provide a script as an example on how to reproduce?

**Comment by kharybdys** [comment]
```
    <methods>
        <method name="matchreport/InitTest"/>
    </methods>
    <message name="Input">
        <property name="MemoField" type="memo"/>
    </message>
````
Just put a ```debug="request"```` in the script you're calling

**Comment by DimitrisD** [comment]
Thanks!
