### ISSUE TITLE
mongoquery should append to existing message

### ISSUE THREAD

**Issue by roelofkemp** [Dexels/navajo#443]
If a script creates an arraymessage and later on appends the results of a mongoquery map to the same messagename, it should be added to the existing arraymessage instead of creating a new message.

code example
```
<message name="Target" type="array" />
...
<navajomap.messages>
   <map.mongo_query ... multiple="true" appendTo="'../Target'">
</navajomap.messages>
```

**Comment by DimitrisD** [comment]
[Fixed in](https://github.com/Dexels/enterprise/commit/c9726f126820671a7628caef2ea263c6962ab59e)
