### ISSUE TITLE
(Navajomap) (Callwebservice) locale header attribute not propagated to webservices that are called from navajo webservices

### ISSUE THREAD

**Issue by DimitrisD** [Dexels/navajo#448]
This issue was noticed in clubs.

When a webservice is called by a tipi scirpt with the callService service tag, everything seems to work fine. But when services inside the called service call other services, the locale property from the header is not propagated to the children.

Eg:
personInsertWizardDialog.xml
&nbsp;&nbsp;&nbsp; |--> calls via callwebservice tag :: vla/relation/InitInsertPerson -> locale exists in the header of the request
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; |--> calls via navajomap.callwebservice tag :: vla/include/list/ListOfGenders -> locale does not exist in the header of the request

**Comment by DimitrisD** [comment]
The solution to this issue if to add
```
if (access.getInDoc() != null && access.getInDoc().getHeader() != null
                    && access.getInDoc().getHeader().getHeaderAttribute("locale") != null
                    && access.getInDoc().getHeader().getHeaderAttribute("locale").equals("")) {

    h.setHeaderAttribute("locale", access.getInDoc().getHeader().getHeaderAttribute("locale"));

}
```
after the line https://github.com/Dexels/navajo/blob/a37693088af86ac2e7a4ae3b2087d03599dbc1ac/server/com.dexels.navajo.adapters/src/com/dexels/navajo/adapter/NavajoMap.java#L1504 

My question here @cbrouwer is whether we should add all the header parameters from the parent webservice to the children webservices or the locale only is enough.

**Comment by cbrouwer** [comment]
Just the locale header should be enough.

**Comment by DimitrisD** [comment]
Cool!
