### ISSUE TITLE
(Entity) (EntityDocumentation) Extend mechanism doesn't take into consideration method attribute in the xml response example)

### ISSUE THREAD

**Issue by DimitrisD** [Dexels/navajo#449]
Example http://knvb-test.sportlink.com/entityDocumentation/kbhb/dataservices.

If ClubProgram is selected and xml response is selected, someone would expect the properties that have method response not to be added to the example xml output.

**Comment by cbrouwer** [comment]
XML output is really deprecated and should be removed from the documentation.

**Comment by DimitrisD** [comment]
@kharybdys  fyi

**Comment by kharybdys** [comment]
You see the method="request" properties in the JSON sample (!) output as well.
Not in the actual one

**Comment by DimitrisD** [comment]
The issue is located [here](https://github.com/Dexels/navajo/blob/master/core/com.dexels.navajo.document/src/com/dexels/navajo/document/base/BaseMessageImpl.java#L1799)
The maskMessage process isn't masking the definition message of an array.
