### ISSUE TITLE
(DropdownList) Ability to get the first value displayed in the dropdown

### ISSUE THREAD

**Issue by kharybdys** [Dexels/navajo#459]
Often, when using dropdowns, the second dropdown depends on the selectedvalue in the first dropdown. When generating a dropdown without an empty option, that means it's the first value returned from the query. However, currently I need to query that separately in a SQLMap in order to be able to work with it after.
I'd like to be able to ask the dropdown map something like "$firstValue" and get the value of the first selection back (which can be -1 if empty Option is on). I can put this in a param and be able to work with it after.

**Comment by DimitrisD** [comment]
Isn't the ` $selectedValue` what you are asking for?

Eg if you do  ``` <debug value="$selectedValue"/> ``` inside a DropdownList without having setting it first, you get the default selection (Name : "-", Value: "-1" ):

 --------- NAVAJO CONSOLE OUTPUT: xxx.xx.xxxxxxx
DEBUG: -1

--------- NAVAJO CONSOLE OUTPUT

**Comment by kharybdys** [comment]
No, it doesn't do what I want. In both these cases I want "ZA" as a result (using KNVB):
```
    <message name="Test">
	    <map.dropdown datasource="'sportlinkkernel'" emptyOption="false" name="'DropdownEmpty'" direction="'in'">
	       <dropdown.query>
	           SELECT codeid, codedesc
	           FROM   codetable
	           WHERE typeofcode = 'GAME_TYPE'
	           AND language = get_default_language()
	           ORDER BY codeid DESC
	       </dropdown.query>
	       <debug value="'SelectedValue: ' + $selectedValue"/>
	    </map.dropdown>

        <map.dropdown datasource="'sportlinkkernel'" emptyOption="false" name="'DropdownWrongValue'" direction="'in'" selectedValue="'MARTE'">
           <dropdown.query>
               SELECT codeid, codedesc
               FROM   codetable
               WHERE typeofcode = 'GAME_TYPE'
               AND language = get_default_language()
               ORDER BY codeid DESC
           </dropdown.query>
           <debug value="'SelectedValue: ' + $selectedValue"/>
        </map.dropdown>
    </message>
```

**Comment by DimitrisD** [comment]
After discussions with @cbrouwer we concluded that this isn't the purpose/usage of the SelectedValue. Thus this is a wontfix.
