### ISSUE TITLE
Set caching info in entity definition

### ISSUE THREAD

**Issue by roelofkemp** [Dexels/navajo#463]
Make it possible to add caching info in an entity definition. 

For example:
```
<caching max-age="120" private="true" />
```

which could translate to a HTTP Cache Control header.

See: https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/http-caching for other properties that might be set in the caching tag

**Comment by DimitrisD** [comment]
Since caching is only relevant in entities, we are gonna support this with a custom __caching__ message. More tbd.
