### ISSUE TITLE
support HEAD call for entities (from curl)

### ISSUE THREAD

**Issue by roelofkemp** [Dexels/navajo#465]
A curl command with ```--head``` should provide a decent description of the entities data:

- in JSON format
- containing all data fields, 
- with type information
- and also preferably with indication whether it is a key, whether the key is required etc.

```
curl --head -H "Authorization: Bearer pkev0ojqb9m5muituest820uao" -H "X-Navajo-Instance: KNVB" -H "Accept: application/json" -H "X-Navajo-Version: 0" "http://localhost:9090/entity/common/memberportal/AccountLinkDetails"
```

**Comment by DimitrisD** [comment]
A --head or -XHEAD request cannot support this functionality cause it violates the HTTP protocol.

Instead, we are gonna use a get request with a query parameter to get the definition, eg:
`http://localhost:9090/entity/knvb/voetbalnl/website/Facility?getDefinition=true`
