### ISSUE TITLE
entity name in __entity__ message

### ISSUE THREAD

**Issue by roelofkemp** [Dexels/navajo#466]
Entity calls already have the ```__entity__``` message injected. Could the name of the entity also be added to this message?

Use case:
Entities might extend from a shared base entity with a couple of base properties. Suppose for all these entities there is some shared code that operates on these base properties (for instance via an include tag). This has the problem that for entity A the property is named ```A/Prop1``` and for B it is ```B/Prop1```, etc. With the entity name in the ```__entity__``` message this could be addressed uniformly as:

```[/__entity__/EntityName] + '/Prop1'```

**Comment by DimitrisD** [comment]
Syntax:

```
[/__entity__/name] + '/Prop1'
```

**Comment by cbrouwer** [comment]
What eaxctly is 'Name' in this context? Is it the message name, the name of the entity where it is defined, or the name of the entity where it is mapped?
So for instance, we have a entity defined in scripts/entity/definition/Person.xml
which is mapped with entitymapping.xml at scripts/entity/common/register/
What will be the content of 'Name'?

**Comment by DimitrisD** [comment]
Based on my understanding it should be the message name (in this example Person). What do you think?

**Comment by cbrouwer** [comment]
That makes sense. However I also would like to know the mapped path (or the path from where the entity itself was called). Would it be possible to include this? Otherwise the path where the entity is defined could work too.

**Comment by DimitrisD** [comment]
The latter (include the entity definition path) is easy. Let me check for what it requires for the mapped path.

**Comment by DimitrisD** [comment]
Two new properties added under the \_\_entity\_\_ message, the _DefinitionPath_, which addresses the absolute path where the entity is defined, and the _MappledPath_, which addresses the mapped path
