### ISSUE TITLE
Support for key="false,required" in entity definition

### ISSUE THREAD

**Issue by roelofkemp** [Dexels/navajo#468]
It should be possible to note that a property is required (as input of GET), but not part of a key.

For instance: 
```<property name="AppPlatform" type="string" method="request" key="false,required,id=unique"/>```

However, the entity executes without this property in the input and also the entity documentation doesn't allow this property to be entered in the 'Try it out' mode.

**Comment by DimitrisD** [comment]
As per system design, at the time being a if a property is required for Get, is by definition a key. Thus for the time being this is a won't fix.
