### ISSUE TITLE
(Entity) Not passing along an optional key of type string is treated as an empty string and not null

### ISSUE THREAD

**Issue by kharybdys** [Dexels/navajo#476]
Have an entity with an optional key of type string and call the delete or get, leaving it empty, using the entityDocumentation or even the curl call. The entity layer will add the property (acceptable) with a value of empty string (unacceptable). I'd either want the whole property to be missing or at the very least with a null value.

**Comment by kharybdys** [comment]
You can see this happening with the KBHB dataservices entity TeamPerson (delete modus), https://kbhb-dataservices-test.sportlink-interfaces.net/entityDocumentation/kbhb/dataservices.

**Comment by DimitrisD** [comment]
This is happening of the way BaseMessageImpl and BasePropertyImpl handle copy of messaging on low level code. 

Should be fixed at fb8a3f58604608a2c2eadcb719b1f66c572ba3b7
