### ISSUE TITLE
restart server to pick up change in operation path

### ISSUE THREAD

**Issue by roelofkemp** [Dexels/navajo#479]
Currently you have to restart the server to pick up a change in an entity operation path

example:
if the following operation 
```
<operation service="existing/path/to/A" method="GET"/>
```
changes to
```
<operation service="other/path/to/B" method="GET"/>
```
then, this is only picked up after a restart.

**Comment by aschoneveld** [comment]
It seems to me that the handleEvent() method in EntityMapper is never called.
In Kibana I cannot find any references to "Updating mappings for" which is an INFO log message that occurs in case of changes. I can locate the log lines of the activate() in Kibana. The handleEvent() method should be listening to the topic "repository/change". According to the declarative service definition it does. This requires further investigation.
