### ISSUE TITLE
(Entity) No recompilation on test/production when mapping file or entity file changes?

### ISSUE THREAD

**Issue by kharybdys** [Dexels/navajo#492]
Two observations:
On production an entity got changed from calling webservice A to calling webservice B (who then calls A again). Other than the webservice used in the GET (only mode), nothing got changed in the entity. After pushing this to production, we couldn't get it to fire the new logic, using the entityDocumentation interface. It did fire the entity but the entity still called webservice A. Conclusion: Entity didn't recompile. Solution: Restart server.

On test I added an entity to the end of a mapping file and pushed that to test. However, even pressing Ctrl-F5 on the entityDocumentation page didn't display it. After a restart of the server it did.

Locally I cannot recreate the first or the second issue, although it is interesting to note that the compilation of the added entity only takes place when I reload the entityDocumentation page (F5).

Stefan reports that this type of change to entities are done often by the app team and they haven't noticed any problems with it.

**Comment by kharybdys** [comment]
Just pushed a new entity to test and restart was not necessary to pick it up. The previous time, the entity already existed but wasn't "active" and only the mapping file was changed, to uncomment the entity.

**Comment by kharybdys** [comment]
Seems duplicate with #479

**Comment by gballintijn** [comment]
#479 has been closed with a solution; does that also solve this problem?

**Comment by kharybdys** [comment]
I described two situations. Since the first situation is exactly what is described in #479 I will consider that solved without testing. I just tried to reproduce the second situation on test but it all worked as expected.
So yes I'd say close the issue.
