### ISSUE TITLE
(Navascript) Add a condition tag

### ISSUE THREAD

**Issue by rfrankhuizen** [Dexels/navajo#507]
This is to avoid the usage of message mode="ignore" when you only really want to group a set of statements under a single condition without having to repeat said condition.

Marte agrees this would be a good extension (she is typing this)

Suggested format:
```
<condition expression="Some expression to be evaluated">
</condition>
```

**Comment by billgemist** [comment]
@rfrankhuizen Maybe the name will be like this? In order not to have too many "condition"
`<block condition="Some expression to be evaluated">
  </block>`

**Comment by rfrankhuizen** [comment]
Yes, even better!

**Comment by rfrankhuizen** [comment]
Added
