### ISSUE TITLE
Navajo Document does not use proper indexes any more

### ISSUE THREAD

**Issue by flyaruu** [Dexels/navajo#512]
The integration tests started failing a while back, and it turns out that the indexes don't work properly and more.

First, the issue:

I run a simple query script that results in an array message:

```xml
<tml documentImplementation="SAXP">
   <header queueId="normalPool" queueSize="0" authorisationTime="1" cpuload="-1.0" requestParseTime="2" threadCount="0" processingTime="13" threadName="normalPool_5" queueTime="1" accessId="1570213224647-13" afterServiceTime="0" beforeServiceTime="0" postTime="2" serverTime="15">
      <transaction rpc_pwd="" rpc_name="movie/ActorList" rpc_usr="exampleuser"/>
      <callback/>
      <client/>
   </header>
   <message name="ActorList">
      <message name="Actor" type="array">
         <message name="Actor" index="0" type="array_element">
            <property name="Id" type="integer" value="1" direction="out"/>
            <property name="FirstName" type="string" value="Penelope" direction="out"/>
            <property name="LastName" type="string" value="Guiness" direction="out"/>
         </message>
         <message name="Actor" index="0" type="array_element">
            <property name="Id" type="integer" value="2" direction="out"/>
            <property name="FirstName" type="string" value="Nick" direction="out"/>
            <property name="LastName" type="string" value="Wahlberg" direction="out"/>
         </message>
    </message>
</tml>
```

As you can see, all array elements have index 0
This is rarely an actual problem, but we should fix this nonetheless

Debugging and fixing this problem shouldn't be too hard, but I'd like to use this opportinity to point to a few tools we have (but few use).

Bugs like this seem suitable for a unit test:

[JUnit for navajo](https://github.com/Dexels/navajo/wiki/junit-for-navajo)

It showed up in the automatic testing suite with our navajo example

[Navajo Example](https://github.com/Dexels/navajo/wiki/Navajo-example)
[Navajo Example Test)](https://github.com/Dexels/navajo/wiki/Navajo-Example-Test)

**Comment by billgemist** [comment]
fixed.
