### ISSUE TITLE
(REST) Extend the RESTAdapter with logging when debug=true

### ISSUE THREAD

**Issue by kharybdys** [Dexels/navajo#516]
It might be nice to have the RESTAdapter output all headers and if necessary the request body, or even made up to be a curl call you can copy from output directly, of the request it is about to send.
But this only when the adapter gets a debug=true (where it would be nice if it would take this from the script level if set there, like SQLMap).
For curl call example, the entityDocumentation logic already does this.

**Comment by billgemist** [comment]
May I have a script for test purposes for the calls?

**Comment by kharybdys** [comment]
I just mailed you a script
