### ISSUE TITLE
Prometheus support for Navajo

### ISSUE THREAD

**Issue by billgemist** [Dexels/navajo#522]
Preliminary investigation for implementing Prometheus monitoring.

**Comment by billgemist** [comment]
What we'd like to achieve is an endpoint at the path "/metrics" (preferably, if not possible any path will do but this will require extra configuration for the monitor application), that returns metrics suitable for consumption by Prometheus (see: https://prometheus.io/docs/instrumenting/exposition_formats/).

The metrics we want exposed are similar to those currently exposed by Rackermon:

- number of threads available in the normal pool
- number of threads in active use from the normal pool (at the moment of scraping)
- number of requests queued for the normal pool (at the moment of scraping)
- number of exceptions (whatever the number is that rackermon now exposes)
- memory usage (at the moment of scraping)
- memory available (at the moment of scraping)
- current status servlet status code (at the moment of scraping)

**Comment by gballintijn** [comment]
The basic implementation should be in dexels.repository since also project there need monitoring. See Dexels/dexels.repository#17.

**Comment by gballintijn** [comment]
Memory usage and availability is implemented by the Prometheus code in dexels.repository.

**Comment by gballintijn** [comment]
Navajo itself currently (com.dexels.navajo.queuemanager, 3.1.16) supports:

- maximum number of threads in normal pool,
- number of active threads in normal pool, and
- number of queued requests for the normal pool.

**Comment by gballintijn** [comment]
Added: 

- `navajo_exceptions_total` - The total count of requests with exceptions during execution.
- `navajo_requests_total` - Total count of requests with exceptions successfully handled.

**Comment by gballintijn** [comment]
Navajo itself currently (com.dexels.navajo.queuemanager:3.1.16, com.dexels.navajo.core:5.3.60) supports:

- `navajo_normal_threadpool_size` - The maximum number of threads in the "normal" thread pool.
- `navajo_active_normal_request_count` - The number of active threads/requests in the "normal" thread pool.
- `navajo_queued_normal_request_count` - The number of queued requests for the "normal" thread pool.
- `navajo_exceptions_total` - The total count of requests with exceptions during execution.
- `navajo_requests_total` - Total count of requests with exceptions successfully handled.
