### ISSUE TITLE
(Target platform) Missing Mysql driver version 8.0

### ISSUE THREAD

**Issue by kharybdys** [Dexels/navajo#538]
For my private hobby project I'm missing support for Mysql version 8.0. It would be cool if this could be added to the Navajo target platform!

**Comment by kharybdys** [comment]
Changes to the navajo platform available in branch _fb_mysql80. These changes are necessary to use the new Mysql 8.0 driver

**Comment by gballintijn** [comment]
Added to `container.cfg` in `dexels-base`.
