### ISSUE TITLE
(NavajoMap) Jumping to different server fails with Invalid Password or other exception on prod/acceptance

### ISSUE THREAD

**Issue by kharybdys** [Dexels/navajo#543]
I was trying to make a systematic that allows me to ensure certain webservices are always executed on certain server(s), in this case the knvb-* servers. When I tested it locally, calling a script on knvb-test, everything worked fine. When I deployed it to production, I got numerous Invalid Password errors.

I just compared local vs acceptance when calling a script on acceptance.
Script is InitTest.xml:
```
<?xml version="1.0" encoding="UTF-8"?>
<navascript xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.navajo.nl/schemas/navascript.xsd">
    <map.navajomap server="'knvb-acceptance.sportlink.com/navajo'">
        <navajomap.callwebservice name="'matchreport/InitTest'" append="'/'"/>
    </map.navajomap>
</navascript>
```

When run locally (talking to acceptance DB) from the tester interface, this works fine and I get the output expected.
When run from the acceptance tester interface, after pushing this script to acceptance, I get the following error:
```
com.dexels.navajo.document.base.NavajoExceptionImpl: java.lang.Exception: missing end tag near line 6, column 0
```

The only important difference between these two tests I can think of would be the Async implementation used (Apache vs Jetty).

Note that if there is a reason to change NavajoMap, I would love to have the option to specify the tenant together with the server in such a switch. There is already a field tenant but this is ignored when using server. Being able to specify tenant allows me to define a similar switch for localhost which does not automagically set tenant in the HTTP Headers due to being true multi-tenant. This is however an optional improvement.

**Comment by gballintijn** [comment]
The problem also does not occur in the test environment.

**Comment by gballintijn** [comment]
The async-jetty bundle has been installed om knvb-acc, knvb-training, knvb-prod, and other-prod.

**Comment by kharybdys** [comment]
In order to be able to use my systematic I would need the async-jetty bundle on all prod servers that run Navajo (app, voetbal etc etc). Just knvb-prod and other-prod is not sufficient. Has it arrived on all other prod pods in the meantime?

**Comment by gballintijn** [comment]
The async-jetty bundle has been installed om app-prod, app-wz-prod, app-sportlinked-prod, voetbalnl-prod, voetbalnl-site-prod, and data-service-prod.

**Comment by gballintijn** [comment]
Can we considered this issue to be done and close it?

**Comment by kharybdys** [comment]
Yes. I do still need to re-apply my change one day to actually verify but our analysis was sound
