### ISSUE TITLE
Create a separate repository for Tipi

### ISSUE THREAD

**Issue by gballintijn** [Dexels/navajo#572]
There is a commercial desire to have a separate (closed) repository for the Tipi source.

This work includes:

- Cloning/forking the navajo repository (see GitHub: [duplicating a repository](https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/duplicating-a-repository))
- Cleaning out both repositories.
- Updating the maven and PDE files in both repositories.
- Updating the build structure (_e.g._, CircleCI).

**Comment by jrtaal** [comment]
TODO

- [x] A fork from navajo is made: https://github.com/dexels/tipi
- [x] Preliminary p2 definition (in  setup/com.dexels.navajo.tipi.p2)
- [x] CircleCI step to build tipi_p2.zip file and upload to CCI as artifact

- [ ] Check whether all features are include in tipi p2 definition (Gerco).
- [ ] Fix & enable tests, if any (Gerco)
- [ ] Remove streams, navajo and vaadin p2 targets files  (Jacco)
- [ ] Remove unneeded source files (Jacco) 
- [ ] cleanup circleci config (Jacco)
- [ ] Update enterprise CI workflow to use tipi.p2  (Jacco)
