### ISSUE TITLE
(Core) Support for math operations on Long type

### ISSUE THREAD

**Issue by StefanICT** [Dexels/navajo#590]
Currently the code below will crash at runtime:

`ToLong(15) + ToLong(10)`
`ToLong(15) - ToLong(10)`
`ToLong(15) / ToLong(10)`

This will return null/empty.

`ToLong(15) * ToLong(10)`

**Comment by gballintijn** [comment]
Created sportlink test branch [_fb_N590_long_math](https://github.com/Dexels/sportlink/tree/_fb_N590_long_math).

**Comment by gballintijn** [comment]
Created navajo fix branch [_fb_N590_long_math](/Dexels/navajo/tree/_fb_N590_long_math).

**Comment by gballintijn** [comment]
Released as bundle `com.dexels.navajo.document` version `3.6.36`.
