### ISSUE TITLE
Build a CSS based DescriptionProvider for Navajo

### ISSUE THREAD

**Issue by flyaruu** [Dexels/navajo#68]
All the infrastructure is there, shouldn't be a big deal, things to remember:
- Performance is very important, the whole thing shouldn't take more than a few millis.
- OSGi integration should be very easy, backporting to non OSGi might prove trickier.
- Decide how to structure the css files.

Design decisions:

_How would we structure the files?_
- We could allow a stylesheet for each script?
- Allow separate style sheets per package?
- Use a single style sheet per language
- There are multiple uses here: Create more consistent TML (by making sure for example that lengths are the same, the subtypes match, etcetera), but also internationalization. Both uses will probably have different requirements on how to structure the css files.
- I am unsure if we need css classes here. In that case we _should_ be able to add classes to Navajo, messages, properties and selections (?)

I'm talking in the TML context now, but these issues also apply to Tipi. The current solution of explicitly applying a CSS by referencing a URL is the ultimate in flexibility, but verbose and can turn into a mess as the number of sheets and amount of CSS code grows.

TO DO:
- Create a dom model on top of TML
- Maybe this is the moment to introduce descriptions to selections in selection properties.
- Introduce class annotations to Navajo Document elements

**Comment by DimitrisD** [comment]
This isn't still relevant, isn't it?
@flyaruu @cbrouwer
