### ISSUE TITLE
Authentication api is messy (com.dexels.navajo.authentication.api)

### ISSUE THREAD

**Issue by flyaruu** [Dexels/navajo#71]
The AAAInterface requires way too many and obscure methods, presumably sportlink related:

I think there are regions ('district') in the api. Makes sense to sportlink, not to the rest of the world
The token authentication and roles aren't well defined in the api, and some return values are unclear. 

I guess we should investigate the link between these methods and the Sportlink Repository, and maybe move some of them there. As an authentication interface we might get away with:

boolean isAuthenticated(Header h)

**Comment by cbrouwer** [comment]
This is now refactored a bit. The new main authentication method is:
```process(Access access) throws AuthorizationException```

I agree with that the reference to districts/regions is not very pretty. There seems to be limited to the ```getUserDistricts()``` method - this should be moved to a Sportlink-specific interface.
