### ISSUE TITLE
Handle HTTP timeouts

### ISSUE THREAD

**Issue by aschoneveld** [Dexels/navajo#86]
HTTP requests can linger for a veeeery long time within the framework:

java.net.SocketInputStream.socketRead0 (SocketInputStream.java:-2)
java.net.SocketInputStream.read (SocketInputStream.java:129)
java.io.BufferedInputStream.fill (BufferedInputStream.java:218)
java.io.BufferedInputStream.read1 (BufferedInputStream.java:258)
java.io.BufferedInputStream.read (BufferedInputStream.java:317)
sun.net.www.http.HttpClient.parseHTTPHeader (HttpClient.java:687)
sun.net.www.http.HttpClient.parseHTTP (HttpClient.java:632)
sun.net.www.protocol.http.HttpURLConnection.getInputStream (HttpURLConnection.java:1200)
java.net.HttpURLConnection.getResponseCode (HttpURLConnection.java:379)
com.dexels.navajo.client.NavajoClient.doTransaction (NavajoClient.java:459)
com.dexels.navajo.client.NavajoClient.doSimpleSend (NavajoClient.java:613)
com.dexels.navajo.adapter.NavajoMap.setDoSend (NavajoMap.java:600)
clubsites.nl.clubprogramma_KNVB.execute (clubprogramma_KNVB.java:77)

**Comment by cbrouwer** [comment]
Commit 31477deaff65680324ac7e1844cf1b01c9296389 allows to control this timeout from the navajomap. 

````
<map.navajomap server="<...>" serverTimeout="30000" >
               (...)
 </map.navajomap>
````
