### ISSUE TITLE
(Tipi) Ensure onValueChanged is fired when Enter is pressed in a TextPropertyField (possibly in more property fields)

### ISSUE THREAD

**Issue by kharybdys** [Dexels/navajo#92]
On a one-line property field, the user expects some behaviour when pressing enter. Specifically, behaviour that is typically implemented in an onValueChanged event block.
In this case, Enter represents "commit"/"save", but shouldn't lose focus of the element.

**Comment by DimitrisD** [comment]
Enter indeed should represent a "save" lets say operation, but the focus behaviour is something custom, according to the design of the system. Most of the ui guidelines suggest that after an "enter" click event on an editable field, the field should lose focus and the cursor should move to the next line (example : google docs, excel, etc). So it would be good if the behaviour in tipi would be the same.
